// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgokgnhsjeayfrjytbjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnb2tnbmhzamVheWZyanl0Ymp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjIwOTQsImV4cCI6MjA2NDk5ODA5NH0.SpwsvFcA8b5dGMbp_LCZaBEZiG_hDjkzXWuw91k-JvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);